services:
    server:
        container_name: server
        build:
            dockerfile: Dockerfile.dev
            context: ./
        develop:
            watch:
                - action: sync
                  path: ./
                  target: /app
        ports:
            - 3000:3000
        env_file:
            - ./.env
        healthcheck:
            test: ["CMD", "curl", "-f", "http://127.0.0.1:3000/ping"]
            interval: 20s
            timeout: 10s
            retries: 5
            start_period: 5s
        command: air
        # volumes:
        #     - ./server:/app
