root_dir = "."

[command]
dev = [
  "uvicorn main:app --host 0.0.0.0 --port 3000",
  "ngrok http --url=admittedly-adequate-scorpion.ngrok-free.app 3000",
  ]
prod = []
test = []

[exclude]
dir = [
  "./.git", 
  "./node_modules", 
  "./__pycache__",
  "./.ruff_cache",
  "./.vscode",
  "./.venv",
  ]
file = []
ext = []
