root_dir = "."

[command]
dev = [
  "DEBUG=1 python3 main.py",
  # "celery -A helpers.celery worker --loglevel=info",
]
prod = []
test = []

[exclude]
dir = [
  "./.git",
  "./__pycache__",
  "./.ruff_cache",
  "./.mypy_cache",
  "./.vscode",
  "./.venv",
]
file = []
ext = []
