from typing import Tuple


def get_app_script() -> Tuple[str, str]:
  manifest = """
  {
    "timeZone": "Canada/Toronto",
    "dependencies": {
    },
    "exceptionLogging": "STACKDRIVER",
    "runtimeVersion": "V8",
    "oauthScopes": [
      "https://www.googleapis.com/auth/script.container.ui",
      "https://www.googleapis.com/auth/spreadsheets.currentonly"
      // "https://www.googleapis.com/auth/spreadsheets"
    ]
  }
  """

  # Google app script
  app_script = """
  /*
  This code is auto generated by thinkledger. Do not edit without proper know how.
  */
  function onOpen() {
    SpreadsheetApp.getUi()
      .createMenu('Dynamic Script')
      .addItem('Show Alert', 'testScript')
      .addToUi();
  }

  function testScript() {
    SpreadsheetApp.getUi().alert('Hello from the scripted menu!');
  }
  """

  return app_script, manifest