// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

type FAQ struct {
	Question string
	Answer   string
}

var faqs = []FAQ{
	{
		Question: "How does the software work?",
		Answer: `Our AI-powered accounting software streamlines your bookkeeping
		by using advanced machine learning algorithms. It automatically categorizes
		transactions, reconciles accounts, and generates detailed financial reports.
		Plus, it continuously learns from your data to improve its accuracy and
		efficiency over time, ensuring you get the most reliable insights into
		your financial health`,
	},
	{
		Question: "Is my financial data stored securely?",
		Answer: `Yes, your financial data is securely stored in the Google Drive account
		linked to the email address you used when creating your account. We organize
		your records in a dedicated folder named "ThinkLedger" to ensure both easy
		access and enhanced security.`,
	},
	// {
	// 	question: "Can I integrate with my existing accounting software?",
	// 	answer: `Yes, our platform offers seamless integration with popular
	// accounting software like QuickBooks, Xero, and Sage. We also provide API
	// access for custom integrations with your existing systems.`,
	// },
	{
		Question: "How accurate is the AI in categorizing transactions?",
		Answer: `Our AI achieves over 95% accuracy in transaction categorization
		from day one. As it learns from your corrections and patterns, accuracy
		typically improves to 98-99% within the first few months of use.`,
	},
	{
		Question: "Do I still need an accountant if I use your software?",
		Answer: `While our AI handles day-to-day bookkeeping and reporting,
		we recommend maintaining a relationship with an accounting professional
		for strategic advice, tax planning, and compliance oversight. Many
		accountants use our platform to collaborate with clients more efficiently.`,
	},
	{
		Question: "What kind of support do you offer?",
		Answer: `We currently provide support exclusively via email. Our dedicated
		support team is ready to help with any questions or concerns you may have,
		and we strive to respond promptly and thoroughly. Please feel free to reach
		out to us at support@thinkledger.app for assistance.`,
	},
}

func FAQs() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"space-y-4\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, faq := range faqs {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"faq-item border-b-2 border-gray-300 rounded-lg overflow-hidden\"><button class=\"flex justify-between items-center w-full p-4 text-left rounded-lg\" aria-expanded=\"false\"><h3 class=\"text-lg font-medium\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(faq.Question)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/components/faq.templ`, Line: 58, Col: 51}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</h3><svg class=\"faq-icon w-5 h-5\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\" xmlns=\"http://www.w3.org/2000/svg\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M19 9l-7 7-7-7\"></path></svg></button><div class=\"faq-answer px-4\"><p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(faq.Answer)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/components/faq.templ`, Line: 64, Col: 20}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</p></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
