// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Logo() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"flex items-center justify-center\"><div><h3 class=\"text-xl\">ThinkLedger</h3></div><div class=\"ms-2 h-[1rem]\"><svg viewBox=\"0 0 240 120\" xmlns=\"http://www.w3.org/2000/svg\" class=\"w-auto h-full\"><path d=\"M20 80\n\t\t\t\t L40 40\n\t\t\t\t L80 20\n\t\t\t\t L100 60\n\t\t\t\t L120 100\n\t\t\t\t L140 40\n\t\t\t\t L160 20\n\t\t\t\t L180 70\n\t\t\t\t L200 100\n\t\t\t\t L220 30\" stroke=\"#0065FA\" fill=\"none\" stroke-width=\"15\" stroke-linejoin=\"miter\" stroke-dasharray=\"1000\" stroke-dashoffset=\"1000\"><animate attributeName=\"stroke-dashoffset\" from=\"1000\" to=\"0\" dur=\"1.5s\" fill=\"freeze\" begin=\"0.5s\" calcMode=\"spline\" keySplines=\"0.4 0 0.2 1\" repeatCount=\"indefinite\"></animate></path></svg></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
