// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package auth

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

const homeTitle string = "Home"
const homeMetaDescription string = "ThinkLedger | Home page"
const homeScript string = "/static/dist/home.js"

func HomePage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, " <div class=\"flex-1 flex flex-col overflow-hidden\"><header class=\"h-16 border-b border-gray-200 dark:border-gray-800 bg-white dark:bg-gray-800 flex items-center px-4\"><button id=\"mobile-toggle\" class=\"p-2 rounded-md hover:bg-gray-100 dark:hover:bg-gray-700 md:hidden\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"lucide lucide-menu\"><line x1=\"4\" x2=\"20\" y1=\"12\" y2=\"12\"></line> <line x1=\"4\" x2=\"20\" y1=\"6\" y2=\"6\"></line> <line x1=\"4\" x2=\"20\" y1=\"18\" y2=\"18\"></line></svg></button><h1 class=\"text-lg font-semibold ml-4 text-gray-800 dark:text-white\">Dashboard</h1></header><main class=\"flex-1 overflow-y-auto p-4 bg-gray-100 dark:bg-gray-900\"><div class=\"max-w-7xl mx-auto\"><h2 class=\"text-2xl font-bold mb-6 text-gray-800 dark:text-white\">Welcome to the Dashboard</h2><div class=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6\"><div class=\"bg-white dark:bg-gray-800 rounded-lg shadow p-6\"><h3 class=\"text-lg font-semibold mb-2 text-gray-800 dark:text-white\">Card Title</h3><p class=\"text-gray-600 dark:text-gray-300\">This is a sample card with some content.</p></div><div class=\"bg-white dark:bg-gray-800 rounded-lg shadow p-6\"><h3 class=\"text-lg font-semibold mb-2 text-gray-800 dark:text-white\">Card Title</h3><p class=\"text-gray-600 dark:text-gray-300\">This is a sample card with some content.</p></div><div class=\"bg-white dark:bg-gray-800 rounded-lg shadow p-6\"><h3 class=\"text-lg font-semibold mb-2 text-gray-800 dark:text-white\">Card Title</h3><p class=\"text-gray-600 dark:text-gray-300\">This is a sample card with some content.</p></div></div></div></main></div> <div id=\"mobile-overlay\" class=\"fixed inset-0 bg-black bg-opacity-50 z-20 hidden md:hidden\"></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = AuthLayout(homeTitle, homeMetaDescription, homeScript).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
