name: tests

on: [push, pull_request]
  # pull_request:
  #   branches: [main, staging]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies && run linters
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv sync --frozen --no-cache
          ruff check .
          mypy --strict .

      # - name: Run linters
      #   run: |